name: Generate Beautiful Snake Animation

on:
  schedule:
    # Execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate_beautiful_snake_animation:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=random&hues=15&chroma=0.8&colorspace=hsl

      - name: Optimize SVG
        uses: schneegans/dsvg@v1
        with:
          input: dist/snake.svg
          output: dist/snake_optimized.svg

      - name: Add timestamp to SVG
        run: echo "$(date)" >> dist/snake_optimized.svg

      - name: Push snake.svg to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
